Add no_std support
pheki/xts-mode pull request #7
Opened 2022-08-14 16:11 UTC by oberien

2022-08-17 01:37 UTC, pheki requested changes
Thanks a lot! I just have 2 small suggestions.

2022-08-17 01:37 UTC, pheki commented on Cargo.toml
> +std = ["byteorder/std", "cipher/std"]
As we don't currently use their std features, can we just remove both from here?

```
std = []
```

2022-08-17 01:37 UTC, pheki commented on Cargo.toml
> +cipher = { version = "0.4", default-features = false }
I don't think we need to disable `default-features` as cipher doesn't enable `std` by default

2022-08-27 11:28 UTC, oberien commented
Thanks for the review. I've fixed both remarks. Both `cargo test` and `cargo test --no-default-features` as well as compiling against uefi (the no-std target I'm working with) run without problems.

2022-08-30 04:26 UTC, merged

2022-08-30 04:26 UTC, pheki commented
Tested and merged it.

Thanks again :)